### ISSUE TITLE
win10 paste_sql_result在console的中文显示乱码

### ISSUE THREAD

**Issue by VinaTsai** [JiaxiangBU/add2impala#3]
#### 在console显示乱码
![image](https://user-images.githubusercontent.com/45908788/89635085-031daa00-d8d9-11ea-9dfd-5b758efad91f.png)

#### debugonce(paste_sql_result2) debug 结果：
1. 每一句都没问题（其他不在这里展示）
![image](https://user-images.githubusercontent.com/45908788/89635051-f436f780-d8d8-11ea-8690-951eff7a7c8e.png)

1. 剪贴板没问题
![image](https://user-images.githubusercontent.com/45908788/89635133-1cbef180-d8d9-11ea-97b4-82c684cb6af0.png)

* 结论：原因未知，但不影响，可直接用剪贴板的数据。

**Comment by JiaxiangBU** [comment]
@VinaTsai 原因找到了。也就是只要是 `usethis::*_fn` 里面含有 non-ASCII 的字符，不转换成 unicode 都会有这个问题，但是 print 到 console 是正常显示的，但是在 Rmd 里面 preview 有这个问题。 

> #### 在console显示乱码

应该是 console 没问题，但是 Rmd preview 有问题。
